services:
  database:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3366:3306
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=receitas
      - MYSQL_USER=master
      - MYSQL_PASSWORD=password